<a href="https://colab.research.google.com/github/anshii1311/Machine_learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr = np.array([2,4,3,5,2])
print(arr)
print(np.__version__)

[2 4 3 5 2]
2.0.2


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,7])
print(arr)
print(type(arr))

[1 2 3 4 7]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,3,2]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 3 2]]
2


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print(arr.ndim)


[[[[[1 2 3 4]]]]]
5


In [ ]:
arr = np.array([1,2,3,4])
print(arr[0])

1
